Tests configs
roavellarm/pianopoa pull request #2
Opened 2022-03-05 22:10 UTC by GustavoFSProg

This PR is to do some configs in testes and du some testes

2022-03-08 21:17 UTC, GustavoFSProg commented
I made the tests basics, for the components e and page Home, testing if irts render the component and if execute de styles config. By so far all is working. I change a litle parts of the code and intall react-scripts to run the tests, because its the more ezsy way to run the tests script, And its working fine.

2022-03-09 17:14 UTC, roavellarm reviewed
After all the dependencies updates do the following:

1. Add coverage after dist-ssr (line 12) in the .gitignore file.
2. Create a `jest.config.ts` file at the root directory of the project and add this:
```JS
export default {
  testEnvironment: 'jsdom',
  transform: {
    '^.+\\.tsx?$': 'ts-jest',
  },
  moduleNameMapper: {
    '\\.(gif|ttf|eot|svg|png)$': '<rootDir>/test/__mocks__/fileMock.js',
    '\\.(css|less|sass|scss)$': 'identity-obj-proxy',
  },
  setupFilesAfterEnv: ['<rootDir>/jest.setup.ts'],
}
```
3. Create a `jest.setup.ts` file at the root directory of the project and add this:
```JS
import '@testing-library/jest-dom/extend-expect' // eslint-disable-line
```
4. Create a "test" directory on the root, inside it a "__mock__" directory with a `fileMock.js` file it. So it would be like: `test/__mocks__/fileMock.js`. Copy the following to the file:
```JS
module.exports = 'test-file-stub'
```
5. Do a local backup of all other files you have changed and remove them from this PR. We will separate each concern in a specific branch/PR

2022-03-09 17:14 UTC, roavellarm commented on package.json
> +    "react-scripts": "^5.0.0",
Remove react-scripts, we are using Vite instead

2022-03-09 17:14 UTC, roavellarm commented on package.json
> +    "@types/react-test-renderer": "^17.0.1",
Remove @types/react-test-renderer

2022-03-09 17:14 UTC, roavellarm commented on package.json
> +    "test": "react-scripts test --no-cache --silent --watchAll",
Use jest instead of react-scripts, like this:
```JSON
{
  "test": "jest --no-cache --silent"
}
```

2022-03-09 17:14 UTC, roavellarm commented on package.json
> +    "react-scripts": "^5.0.0",
Also, please add a coverage script so we can check it eventually:
```JSON
{
  "coverage": "jest --coverage --watchAll"
}
```

2022-03-09 17:14 UTC, roavellarm commented on package.json
> +    "react-test-renderer": "^17.0.2",
Remove react-test-renderer

2022-03-09 17:14 UTC, roavellarm commented on package.json
>    },
Add two new DEV dependencies:
```BASH
$ yarn add -D ts-node identity-obj-proxy
```

2022-03-09 17:23 UTC, roavellarm requested changes
Don't forget to remove all the files from this PR.

Do a local backup of them before, so you don't lose your work that we'll just separate it in other PR after we talk about it.

The files to be removed are:

- src/Home/Home.tsx 
- src/Home/style_home.ts 
- src/__test__/Footer.test.tsx 
- src/__test__/Header.test.tsx 
- src/__test__/Home.test.tsx 
- src/__test__/HomeText.test.tsx 
- src/components/Footer/Footer.tsx 
- src/components/Footer/style_footer.ts 
- src/components/Header/header.tsx 
- src/components/Header/style_header.ts 
- src/components/HomeText/HomeText.tsx 
- src/components/HomeText/style_homeText.ts 
- src/styles/styled-app.ts

2022-03-09 18:45 UTC, GustavoFSProg commented
I do the review requests, deleting old files and do the configs in jest,config.ts, jest.setup.ts, in package json, ins the sripts f testing. And remove react-scripts, and reat-test-renderer.  I upload the new files configurations.

2022-03-12 21:09 UTC, roavellarm approved these changes
Nice work! :rocket:

2022-03-12 21:09 UTC, roavellarm commented on src/__test__/App.test.tsx
> -})
Hey @GustavoFSProg,  

Nice work!
Please, can you add this test back and test that the App is rendering the `<h1>Hello World</h1>`?
Here is an example:
```JS
it('should render correctly', () => {
    render(<App />)
    expect(screen.getByRole('heading', { name: /Hello World/i })).toBeInTheDocument()
    // OR use Truthy
    expect(screen.getByRole('heading', { name: /Hello World/i })).toBeTruthy()
})
```

2022-03-12 21:09 UTC, roavellarm commented on src/styles/theme.ts
> -    raleway: 'Raleway, sans-serif',
Please, roll back this space, and in a new PR will do next you can change on the test instead of the theme.ts file.

2022-03-12 21:10 UTC, merged